# Generated by Django 4.0.4 on 2022-05-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
